packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # React ecosystem
  react: ^18.3.1
  react-dom: ^18.3.1
  next: 15.3.4

  # TypeScript types
  '@types/node': ^22
  '@types/react': ^18
  '@types/react-dom': ^18
  '@types/eslint': 8.56.10

  # Build tools
  typescript: 5.8.3
  postcss: 8.5.6
  tailwindcss: 3.4.17
  tailwindcss-animate: 1.0.7
  rimraf: 6.0.1
  tsx: 4.20.3

  # TRPC
  '@trpc/client': 11.4.3
  '@trpc/react-query': 11.4.3
  '@trpc/server': 11.4.3

  # Database
  'drizzle-orm': 0.44.2
  'drizzle-kit': 0.31.4
  postgres: 3.4.7
  dotenv: 17.0.0

  # Utilities
  clsx: 2.1.1
  zod: 3.25.67
  superjson: 2.2.2
  'class-variance-authority': 0.7.1
  'tailwind-merge': 3.3.1
  'server-only': 0.0.1

  # State management
  zustand: 5.0.6
  '@tanstack/react-query': 5.81.5

  # Environment
  '@t3-oss/env-nextjs': 0.13.8

  # Internationalization
  'next-intl': 4.3.1

  # Authentication
  'next-auth': 4.24.11
  '@worldcoin/minikit-js': 1.9.6

  # Development tools
  eruda: 3.2.3
  '@biomejs/biome': 1.9.4
  turbo: 2.5.4

  # ESLint
  eslint: 8.57.0
  '@typescript-eslint/eslint-plugin': 8.1.0
  '@typescript-eslint/parser': 8.1.0
  'eslint-config-next': 14.2.4
  'eslint-plugin-tailwindcss': 3.17.5
  'eslint-plugin-unused-imports': 4.1.4
