import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ErudaProvider } from "~/components/Eruda";
import MiniKitProvider from "~/components/minikit-provider";
import NextAuthProvider from "~/components/next-auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <ErudaProvider>
            <MiniKitProvider>
              <div className={inter.className}>{children}</div>
            </MiniKitProvider>
          </ErudaProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
